CREATE TABLE ProductType
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE Brand 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL UNIQUE
)

CREATE TABLE Product 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NULL,
	PurchasePrice DECIMAL(18,2) NOT NULL,
	SalePrice DECIMAL(18,2) NOT NULL,
	BrandId INT NOT NULL,
	ProductTypeId INT NOT NULL,

	CONSTRAINT FK_Product_Brand FOREIGN KEY (BrandId) REFERENCES Brand(Id),
	CONSTRAINT FK_Product_ProductType FOREIGN KEY (ProductTypeId) REFERENCES ProductType(Id),
)

CREATE TABLE City
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL
)

CREATE TABLE Store 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	CityId INT NOT NULL,
	[Address] NVARCHAR(100) NOT NULL,

	CONSTRAINT FK_Store_City FOREIGN KEY (CityId) REFERENCES City(Id)
)

CREATE TABLE Customer 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[Surname] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL UNIQUE,
	[Address] NVARCHAR(MAX) NOT NULL,
	CityId INT NOT NULL,

	CONSTRAINT FK_Customer_City FOREIGN KEY (CityId) REFERENCES City(Id)
)

CREATE TABLE [Date] 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Date] DATETIME NOT NULL UNIQUE,
	[DayOfWeek] TINYINT NOT NULL,
	[WeekOfMonth] TINYINT NOT NULL,
	[WeekOfYear] INT NOT NULL,
	[Month] TINYINT NOT NULL,
	[Quarter] TINYINT NOT NULL,
	[Year] INT NOT NULL
)

CREATE TABLE FactSale
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	CustomerId INT NOT NULL,
	ProductId INT NOT NULL,
	StoreId INT NOT NULL,
	DateId INT NOT NULL,
	TotalSalePrice DECIMAL(18,2) NOT NULL,
	Units INT NOT NULL,
	TotalPurchasePrice DECIMAL(18, 2) NOT NULL,

	CONSTRAINT FK_FactSale_Customer FOREIGN KEY (CustomerId) REFERENCES Customer(Id),
	CONSTRAINT FK_FactSale_Product FOREIGN KEY (ProductId) REFERENCES Product(Id),
	CONSTRAINT FK_FactSale_Store FOREIGN KEY (StoreId) REFERENCES Store(Id),
	CONSTRAINT FK_FactSale_Date FOREIGN KEY (DateId) REFERENCES [Date](Id),
)

CREATE TABLE Supplier 
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(100) NOT NULL,
	[Email] NVARCHAR(100) NOT NULL UNIQUE,
	[Address] NVARCHAR(MAX) NOT NULL,
	CityId INT NOT NULL,

	CONSTRAINT FK_Supplier_City FOREIGN KEY (CityId) REFERENCES City(Id)
)

CREATE TABLE FactPurchase
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	SupplierId INT NOT NULL,
	ProductId INT NOT NULL,
	DateId INT NOT NULL,
	TotalPrice DECIMAL(18,2) NOT NULL,
	Units INT NOT NULL,

	CONSTRAINT FK_FactPurchase_Supplier FOREIGN KEY (SupplierId) REFERENCES Supplier(Id),
	CONSTRAINT FK_FactPurchase_Product FOREIGN KEY (ProductId) REFERENCES Product(Id),
	CONSTRAINT FK_FactPurchase_Date FOREIGN KEY (DateId) REFERENCES [Date](Id),
)

--CREATE TABLE Payment
--(
--	Id INT PRIMARY KEY IDENTITY(1,1),
--	DateId
--	TypeId
--	StatusId --zakucani kje treba da bidat
--)

CREATE TABLE SupplierBrand (
	Id INT PRIMARY KEY IDENTITY(1,1),
	SupplierId INT NOT NULL,
	BrandId INT NOT NULL,

	CONSTRAINT FK_SupplierBrand_Brand FOREIGN KEY (BrandId) REFERENCES Brand(Id),
	CONSTRAINT FK_SupplierBrand_Supplier FOREIGN KEY (SupplierId) REFERENCES Supplier(Id),
)