--CREATE FUNCTION dbo.Cyrillic2Latin_tv (@String nvarchar(MAX))
--RETURNS TABLE
--AS RETURN(
--    SELECT REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(@string,N'ый',N'y'),N'ЫЙ',N'Y'),N'а',N'a'),N'б',N'b'),N'в',N'v'),N'г',N'g'),N'д',N'd'),N'е',N'e'),N'ё',N'yo'),N'ж',N'zh'),N'з',N'z'),N'и',N'i'),N'й',N'y'),N'к',N'k'),N'л',N'l'),N'м',N'm'),N'н',N'n'),N'о',N'o'),N'п',N'p'),N'р',N'r'),N'с',N's'),N'т',N't'),N'у',N'u'),N'ф',N'f'),N'х',N'kh'),N'ц',N'c'),N'ч',N'ch'),N'ш',N'sh'),N'щ',N'shch'),N'ъ',N''),N'ы',N'y'),N'ь',N''),N'э',N'e'),N'ю',N'yu'),N'я',N'ya'),N'А',N'A'),N'Б',N'B'),N'В',N'V'),N'Г',N'G'),N'Д',N'D'),N'Е',N'E'),N'Ё',N'YO'),N'Ж',N'ZH'),N'З',N'Z'),N'И',N'I'),N'Й',N'Y'),N'К',N'K'),N'Л',N'L'),N'М',N'M'),N'Н',N'N'),N'О',N'O'),N'П',N'P'),N'Р',N'R'),N'С',N'S'),N'Т',N'T'),N'У',N'U'),N'Ф',N'F'),N'Х',N'KH'),N'Ц',N'C'),N'Ч',N'CH'),N'Ш',N'SH'),N'Щ',N'SHCH'),N'Ъ',N''),N'Ы',N'Y'),N'Ь',N''),N'Э',N'E'),N'Ю',N'YU'),N'Я',N'YA') AS NonCyrillic
--);

---

DECLARE @CustomerNumber INT = 0
DECLARE @Num INT
DECLARE @Name NVARCHAR(100)
DECLARE @Surname NVARCHAR(100)
DECLARE @Email NVARCHAR(100) = NULL
DECLARE @Address NVARCHAR(100)
DECLARE @CityId INT

WHILE(@CustomerNumber < = 50)
BEGIN

---@Name

SET @Num = ROUND(RAND()*155,0) + 1
SET @Name = CHOOSE(@Num, 
N'Аврам', 
N'Александар', 
N'Алимпиј', 
N'Атанас', 
N'Ангел', 
N'Андон', 
N'Андреј', 
N'Антим', 
N'Антониј', 
N'Апостол', 
N'Аритон', 
N'Арсениј', 
N'Атанасиј', 
N'Благој', 
N'Богатин', 
N'Богдан', 
N'Богослав', 
N'Божин', 
N'Бојан', 
N'Борис', 
N'Борјан', 
N'Бранко', 
N'Василиј', 
N'Велјан', 
N'Венко', 
N'Веселин', 
N'Виктор', 
N'Владимир', 
N'Војдан', 
N'Војкан', 
N'Гаврил', 
N'Георгиј', 
N'Герасим', 
N'Глигор', 
N'Глигориј', 
N'Горан', 
N'Горјан', 
N'Гоце', 
N'Григор', 
N'Григориј', 
N'Гроздан', 
N'Давид', 
N'Дамјан', 
N'Данаил', 
N'Дејан', 
N'Делјан', 
N'Делчо', 
N'Димитар', 
N'Димитриј', 
N'Дојчин', 
N'Драган', 
N'Душко', 
N'Ѓоко', 
N'Ѓорѓија', 
N'Ѓорче', 
N'Ѓурчин', 
N'Евгениј', 
N'Евтим', 
N'Елисиј', 
N'Еразмо', 
N'Емануел', 
N'Емил', 
N'Ефтим', 
N'Живко', 
N'Зафир', 
N'Захариј', 
N'Здравко', 
N'Златан', 
N'Златко', 
N'Зоран', 
N'Ѕвездан', 
N'Ѕвонко', 
N'Иван', 
N'Игнат', 
N'Игнатиј', 
N'Игор', 
N'Илија', 
N'Иринеј', 
N'Исак', 
N'Јаков', 
N'Јане', 
N'Јоаким', 
N'Јован', 
N'Јордан', 
N'Јосиф', 
N'Кирил', 
N'Климент', 
N'Козма', 
N'Константин', 
N'Костадин', 
N'Крсте', 
N'Кузман', 
N'Кочо', 
N'Лазар', 
N'Лазар', 
N'Леонид', 
N'Лука', 
N'Љубен', 
N'Љубомир', 
N'Љупчо', 
N'Македон', 
N'Мануел', 
N'Марин', 
N'Марјан', 
N'Марко', 
N'Методиј', 
N'Мирко', 
N'Митре', 
N'Михаил', 
N'Наум', 
N'Неделко', 
N'Неофит', 
N'Нестор', 
N'Никита', 
N'Никифор', 
N'Никодим', 
N'Никола', 
N'Огнен', 
N'Оливер', 
N'Павле', 
N'Пантелејмон', 
N'Панче', 
N'Партениј', 
N'Петар', 
N'Петко', 
N'Пимен', 
N'Прокопиј', 
N'Размо', 
N'Рајко', 
N'Ристе', 
N'Ромил', 
N'Самуил', 
N'Силјан', 
N'Симон', 
N'Славе', 
N'Софрониј', 
N'Сотир', 
N'Спасе', 
N'Сребре', 
N'Стефан', 
N'Стојан', 
N'Темелко', 
N'Теодор', 
N'Теодсиј', 
N'Теофан', 
N'Теофил', 
N'Тихомир', 
N'Трајан', 
N'Тодор', 
N'Трифун', 
N'Филип', 
N'Христијан', 
N'Христо', 
N'Цветан', 
N'Часлав', 
N'Чедомир')

---@Surname

SET @Num = ROUND(RAND()*155,0) + 1
SET @Surname = CHOOSE(@Num, 
N'Аврам', 
N'Александар', 
N'Алимпиј', 
N'Атанас', 
N'Ангел', 
N'Андон', 
N'Андреј', 
N'Антим', 
N'Антониј', 
N'Апостол', 
N'Аритон', 
N'Арсениј', 
N'Атанасиј', 
N'Благој', 
N'Богатин', 
N'Богдан', 
N'Богослав', 
N'Божин', 
N'Бојан', 
N'Борис', 
N'Борјан', 
N'Бранко', 
N'Василиј', 
N'Велјан', 
N'Венко', 
N'Веселин', 
N'Виктор', 
N'Владимир', 
N'Војдан', 
N'Војкан', 
N'Гаврил', 
N'Георгиј', 
N'Герасим', 
N'Глигор', 
N'Глигориј', 
N'Горан', 
N'Горјан', 
N'Гоце', 
N'Григор', 
N'Григориј', 
N'Гроздан', 
N'Давид', 
N'Дамјан', 
N'Данаил', 
N'Дејан', 
N'Делјан', 
N'Делчо', 
N'Димитар', 
N'Димитриј', 
N'Дојчин', 
N'Драган', 
N'Душко', 
N'Ѓоко', 
N'Ѓорѓија', 
N'Ѓорче', 
N'Ѓурчин', 
N'Евгениј', 
N'Евтим', 
N'Елисиј', 
N'Еразмо', 
N'Емануел', 
N'Емил', 
N'Ефтим', 
N'Живко', 
N'Зафир', 
N'Захариј', 
N'Здравко', 
N'Златан', 
N'Златко', 
N'Зоран', 
N'Ѕвездан', 
N'Ѕвонко', 
N'Иван', 
N'Игнат', 
N'Игнатиј', 
N'Игор', 
N'Илија', 
N'Иринеј', 
N'Исак', 
N'Јаков', 
N'Јане', 
N'Јоаким', 
N'Јован', 
N'Јордан', 
N'Јосиф', 
N'Кирил', 
N'Климент', 
N'Козма', 
N'Константин', 
N'Костадин', 
N'Крсте', 
N'Кузман', 
N'Кочо', 
N'Лазар', 
N'Лазар', 
N'Леонид', 
N'Лука', 
N'Љубен', 
N'Љубомир', 
N'Љупчо', 
N'Македон', 
N'Мануел', 
N'Марин', 
N'Марјан', 
N'Марко', 
N'Методиј', 
N'Мирко', 
N'Митре', 
N'Михаил', 
N'Наум', 
N'Неделко', 
N'Неофит', 
N'Нестор', 
N'Никита', 
N'Никифор', 
N'Никодим', 
N'Никола', 
N'Огнен', 
N'Оливер', 
N'Павле', 
N'Пантелејмон', 
N'Панче', 
N'Партениј', 
N'Петар', 
N'Петко', 
N'Пимен', 
N'Прокопиј', 
N'Размо', 
N'Рајко', 
N'Ристе', 
N'Ромил', 
N'Самуил', 
N'Силјан', 
N'Симон', 
N'Славе', 
N'Софрониј', 
N'Сотир', 
N'Спасе', 
N'Сребре', 
N'Стефан', 
N'Стојан', 
N'Темелко', 
N'Теодор', 
N'Теодсиј', 
N'Теофан', 
N'Теофил', 
N'Тихомир', 
N'Трајан', 
N'Тодор', 
N'Трифун', 
N'Филип', 
N'Христијан', 
N'Христо', 
N'Цветан', 
N'Часлав', 
N'Чедомир') + N'овски'

---@Email

--WHILE ((SELECT COUNT(Email) FROM Customer WHERE Email = @Email) > 0 AND @Email IS NULL AND @Email = '')
--BEGIN
	SET @Num = ROUND(RAND()*2,0) + 1
	SET @Email = CHOOSE(@Num, N'@gmail.com', '@yahoo.com', '@hotmail.com')

	SET @Email = (SELECT * FROM dbo.Cyrillic2Latin_tv(@Name)) + '.' + (SELECT * FROM dbo.Cyrillic2Latin_tv(@Surname)) + @Email
--END

---@CityId

SET @CityId = ROUND(RAND()*4,0) + 1

---@Address

--SET @Address = (SELECT TOP 1 [Address] FROM Customer ORDER BY NEWID())+'1'
SET @Num = ROUND(RAND()*9,0) + 1
SET @Address = CHOOSE(@Num, 
N'Ул. Глигор Прличев', 
N'Бул. „1-ви Мај“ бр.62', 
N'Херој Карпош 18', 
N'бул.Партизански Одреди 41/2', 
N'Козле 70',
N'Орце Николов 101/7',
N'Никола Карев бр. 7',
N'Даме Груепв бр. 29',
N'Илинден бр 9',
N'Козле 80') + N'овска'

INSERT INTO [dbo].[Customer]
           ([Name]
           ,[Surname]
           ,[Email]
           ,[Address]
           ,[CityId])
     VALUES
           (@Name
           ,@Surname
           ,@Email
           ,@Address
           ,@CityId)

SET @CustomerNumber = @CustomerNumber + 1
--SET @Email = NULL
END

------------------------------------


